version: '3'
services:
  dev:
    container_name: local
    image: eviction-data:latest
    restart: unless-stopped
# Mount your own Streamlit project if you'd like to /app if you'd like. main.py will run automatically
#    volumes:
#      - /home/user/src:/app
# Uncomment this line and add your own custom index as needed (e.g., for injecting Google Analytics or other tracking)
#      - /home/user/custom/index.html:/root/.local/lib/python3.8/site-packages/streamlit/static/index.html
    ports:
      - 8501:8501
    networks:
      - default
    volumes:
      - .:/usr/src/app:rw
    security_opt:
      - no-new-privileges:true
    environment:
      - STREAMLIT_SERVER_PORT=8501 #This needs to match exposed port in Dockerfile. See https://github.com/bigjoedata/streamlit-plus for dockerfile
    # You may need to uncomment these for some use cases
    # - enableCORS=false
    # - enableXsrfProtection=false
    command: streamlit run run.py