version: '3'
services:
  dev:
    container_name: local
    image: eviction-data_dev:latest
    restart: unless-stopped
    ports:
      - 8501:8501
    networks:
      - default
    volumes:
      - .:/usr/src/app:cached
    security_opt:
      - no-new-privileges:true
    environment:
      - STREAMLIT_SERVER_PORT=8501
    # You may need to uncomment these for some use cases
    # - enableCORS=false
    # - enableXsrfProtection=false
    command: streamlit run run.py